version: "3.6"
services:
  gitlab:
    image: "wjchan/gitlab_img:latest"
    container_name: "gitlab"
    restart: always
    hostname: "gitlab.devopsteam1.com"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.devopsteam1.com:8924'
    ports:
      - "8924:8924"
      - "443:443"
      - "22:22"
    volumes:
      - "$GITLAB_HOME/config:/etc/gitlab"
      - "$GITLAB_HOME/logs:/var/log/gitlab"
      - "$GITLAB_HOME/data:/var/opt/gitlab"
    networks: 
      - devopsNet

  sonarqube:
    image: "wjchan/sonarqube_img:latest"
    container_name: "sonarqube"
    restart: always
    hostname: "sonarqube.devopsteam1"
    ports:
      - "9092:9092"
      - "9000:9000"
    networks: 
        - devopsNet

networks:
  devopsNet: {}
