version: "3.7"
services:
  gitlab:
    image: "gitlab/gitlab-ee:latest"
    container_name: "gitlab"
    restart: always
    hostname: "gitlab.devopsteam1:8924"
    volumes:
      - "/srv/gitlab/config:/etc/gitlab"
      - "/srv/gitlab/logs:/var/log/gitlab"
      - "/srv/gitlab/data:/var/opt/gitlab"
    ports:
      - "2222:22"
      - "8080:80"
      - "443:443"
      - "8924:8924"
      - "5555:5555"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8924'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        registry_external_url 'http://localhost:5555'
        registry['enable'] = true
        unicorn['socket'] = '/opt/gitlab/var/unicorn/gitlab.socket'
    networks:
      - devopsNet

  gitlab-runner:
    image: "gitlab/gitlab-runner:latest"
    container_name: "gitlab-runner"
    restart: always
    links:
      - gitlab
    volumes:
      - "/srv/gitlab-runner/config:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - CI_SERVER_URL=http://gitlab:8924/
      - DOCKER_NETWORK_MODE=host
      - RUNNER_NAME=runner
      - RUNNER_TAG_LIST="latest"
      - DOCKER_PRIVILEGED=true
      - RUNNER_EXECUTOR=docker
      - DOCKER_IMAGE="alpine:latest"
      - DOCKER_LINKS="gitlab.devopsteam1:8924"
    networks:
      - devopsNet

  sonarqube:
    image: "sonarqube:latest"
    container_name: "sonarqube"
    restart: always
    hostname: "sonarqube.devopsteam1"
    ports:
      - "9092:9092"
      - "9000:9000"
    networks:
      - devopsNet

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 50003:50000
    container_name: jenkins
    restart: always
    volumes:
      - /srv/jenkins/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devopsNet

networks:
  devopsNet: {}
