version: "3.7"
services:
  gitlab:
    image: "wjchan/gitlab_img:latest"
    container_name: "gitlab"
    restart: always
    hostname: "gitlab.devopsteam1:8924"
    expose:
      - "8924"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://localhost:8924"
    ports:
      - "8924:8924"
    volumes:
      - "$GITLAB_HOME/config:/etc/gitlab"
      - "$GITLAB_HOME/logs:/var/log/gitlab"
      - "$GITLAB_HOME/data:/var/opt/gitlab"
    networks:
      - devopsNet

  gitlab-runner:
    image: "gitlab/gitlab-runner:latest"
    container_name: "gitlab-runner"
    restart: always
    links:
      - gitlab
    volumes:
      - "/srv/gitlab-runner/config:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - CI_SERVER_URL=http://gitlab:8924/
      - DOCKER_NETWORK_MODE=host
      - RUNNER_NAME=runner
      - RUNNER_TAG_LIST="latest"
      - DOCKER_PRIVILEGED=true
      - RUNNER_EXECUTOR=docker
      - DOCKER_IMAGE="alpine:latest"
      - DOCKER_LINKGS="gitlab.devopsteam1:8924"
    networks:
      - devopsNet

  sonarqube:
    image: "wjchan/sonarqube_img:latest"
    container_name: "sonarqube"
    restart: always
    hostname: "sonarqube.devopsteam1"
    ports:
      - "9092:9092"
      - "9000:9000"
    networks:
      - devopsNet

networks:
  devopsNet: {}
